function visualUpdateOfGUIAfterFirstParameter(handles)
%% Visuelles Update in der GUI
dunkelrot=handles.dunkelrot;
hellrot=handles.hellrot;
rosa=handles.rosa;
grau=handles.grau;
gruen=handles.gruen;
axes(handles.axes24)
imshow('.\gui_pics\Mikroskopie_hinterschnitte.png')
axes(handles.axes25)
imshow('.\gui_pics\Mikroskopie_OF-nahe_Poren.png')
axes(handles.axes26)
imshow('.\gui_pics\Mikroskopie_materialinseln.png')
axes(handles.axes27)
imshow('.\gui_pics\Mikroskopie_FlaecheHinterMaterialinseln.png')
axes(handles.axes28)
imshow('.\gui_pics\Mikroskopie_kennwert6.png')
axes(handles.axes29)
imshow('.\gui_pics\Mikroskopie_Einlaufstellen.png')

set(handles.Kennwert2, 'string', 'Berechnen')
set(handles.Kennwert2, 'BackgroundColor',dunkelrot)
set(handles.Kennwert2, 'ForegroundColor','white')
set(handles.Kennwert3, 'string', 'Berechnen')
set(handles.Kennwert3, 'BackgroundColor',dunkelrot)
set(handles.Kennwert3, 'ForegroundColor','white')
set(handles.Kennwert5, 'string', 'Berechnen')
set(handles.Kennwert5, 'BackgroundColor',dunkelrot)
set(handles.Kennwert5, 'ForegroundColor','white')
set(handles.Kennwert6, 'string', 'Berechnen')
set(handles.Kennwert6, 'BackgroundColor',dunkelrot)
set(handles.Kennwert6, 'ForegroundColor','white')
set(handles.Kennwert4, 'string', 'Berechnen')
set(handles.Kennwert4, 'BackgroundColor',dunkelrot)
set(handles.Kennwert4, 'ForegroundColor','white')
set(handles.pushbutton77, 'string', 'OK')
set(handles.pushbutton77, 'BackgroundColor',dunkelrot)
set(handles.pushbutton77, 'ForegroundColor','white')

set(handles.text57,'backgroundcolor','white')
set(handles.text58,'backgroundcolor','white')
set(handles.text59,'backgroundcolor','white')
set(handles.text60,'backgroundcolor','white')
set(handles.text61,'backgroundcolor','white')
set(handles.text62,'backgroundcolor','white')
set(handles.text64,'backgroundcolor',hellrot)
set(handles.AnzahlUnterteilungenText,'backgroundcolor',rosa)


set(handles.uipanel36,'backgroundcolor',hellrot)
set(handles.uipanel36,'highlightcolor',hellrot)
set(handles.uipanel36,'shadowcolor',hellrot)
set(handles.uipanel37,'backgroundcolor',hellrot)
set(handles.uipanel37,'highlightcolor',hellrot)
set(handles.uipanel37,'shadowcolor',hellrot)
set(handles.uipanel39,'backgroundcolor',hellrot)
set(handles.uipanel39,'highlightcolor',hellrot)
set(handles.uipanel39,'shadowcolor',hellrot)
set(handles.uipanel40,'backgroundcolor',grau)
set(handles.uipanel40,'highlightcolor',grau)
set(handles.uipanel40,'shadowcolor',grau)
set(handles.uipanel41,'backgroundcolor',hellrot)
set(handles.uipanel41,'highlightcolor',hellrot)
set(handles.uipanel41,'shadowcolor',hellrot)
set(handles.uipanel9,'shadowcolor',dunkelrot)
set(handles.uipanel9,'highlightcolor',dunkelrot)
set(handles.uipanel9,'backgroundcolor',dunkelrot)
set(handles.uipanel9,'foregroundcolor','white')